# Week 1 — Research Question

## 1. My Lane and Why

### Provisional Lane: Lane 2 — Refresh / Content Opportunity Scoring

**Question:**

Which pages should be reviewed first for refresh, expansion,
protection, pruning, or monitoring?

I chose Lane 2 because the starter dataset contains 30,000
content pages and provides observable performance and content
signals that can be used to prioritize pages for human review.

The starter dataset also shows meaningful movement: 16,262 pages
(54.21%) have a downward trend. The average page has 5,200.37
90-day impressions.

These numbers suggest that there is enough content inventory and
performance variation to investigate a prioritization problem.

This is a provisional lane choice and may be confirmed or changed
as the analysis progresses.

In [3]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current folder:
d:\flyrank\flyrank-ml-main\work\notebooks

Files/folders here:
['w01_research_question.ipynb']


In [4]:
import os

print(os.path.exists("../../data"))
print(os.path.exists("../../data/raw"))
print(os.path.exists("../../data/raw/content_refresh_anonymized.csv"))

False
False
False


In [5]:
import os

# Look for the CSV starting from the repository root
root = r"D:\flyrank\flyrank-ml-main"

matches = []

for folder, subfolders, files in os.walk(root):
    if "content_refresh_anonymized.csv" in files:
        matches.append(os.path.join(folder, "content_refresh_anonymized.csv"))

print("CSV files found:")
for path in matches:
    print(path)

CSV files found:
D:\flyrank\flyrank-ml-main\flyrank-ml-main\data\raw\content_refresh_anonymized.csv


In [6]:
import pandas as pd

df = pd.read_csv("../../flyrank-ml-main/data/raw/content_refresh_anonymized.csv")

print("Total pages:", len(df))
print("Average 90-day impressions:", round(df["impressions_90d"].mean(), 2))
print("Declining pages:", (df["trend_direction"] == "down").sum())

Total pages: 30000
Average 90-day impressions: 5200.37
Declining pages: 16262


## 2. The Question: Decision, Action, and Cost of a Wrong Call

### Decision

Which content pages should be reviewed first for refresh,
expansion, protection, pruning, or monitoring?

### Action

A content team could use the ranked output to decide which pages
to review first, rather than manually reviewing all 30,000 pages.

For each prioritized page, the output should include a suggested
action and clear reason codes so that a human can understand why
the page was prioritized.

### Cost of a Wrong Call

A false recommendation could waste content-review time or lead to
unnecessary changes to a page that is already performing well.

A missed recommendation could also mean that a page needing
attention is not reviewed soon enough.

Therefore, the system should support human review rather than
automatically make content changes.

### Why This Is Not Just "Train a Model"

The goal is not simply to maximize a model metric.

The goal is to produce a useful and interpretable review queue.
A transparent baseline should be compared with any ML approach,
and the final recommendations should include reasons that a
content team can understand.

The analysis should also distinguish association from causation:
a signal associated with declining performance does not prove
that changing that signal will improve the page.

## 3. Quick Look at the Data

The starter dataset contains **30,000 content pages**.

The average page has **5,200.37 impressions over the last 90 days**.

There are **16,262 pages with a downward trend**, which is **54.21%** of the dataset.

These numbers make the refresh/opportunity prioritization problem worth
investigating because there is a large content inventory and observable
variation in page performance.

These numbers are descriptive evidence from the starter dataset. They
do not show that a refresh will improve a page's performance.

In [7]:
print("Number of content pages:", len(df))
print("Average 90-day impressions:", round(df["impressions_90d"].mean(), 2))

declining_pages = (df["trend_direction"] == "down").sum()
print("Declining pages:", declining_pages)
print("Declining percentage:", round(declining_pages / len(df) * 100, 2), "%")

Number of content pages: 30000
Average 90-day impressions: 5200.37
Declining pages: 16262
Declining percentage: 54.21 %


## 4. Careful Words: What I Can and Can't Claim

### What I Can Claim

- The starter dataset contains 30,000 content pages.
- 16,262 pages (54.21%) have a downward trend in the available
  starter label.
- The dataset contains observable performance and content signals
  that can be used to investigate page prioritization.
- These signals can be tested for their association with the
  selected outcome and used to build a review-prioritization
  approach.

### What I Cannot Claim

- I cannot claim that a particular signal causes a page's
  performance to decline.
- I cannot claim that refreshing a page will definitely improve
  its performance.
- I cannot claim that the analysis has discovered or proven a
  search-engine ranking algorithm factor.
- I cannot treat a model's prediction as a guaranteed business
  outcome.
- I cannot use future information to make a recommendation about
  an earlier decision.

The analysis is intended to support human review and prioritization,
not to automatically decide what should happen to a page.

## 5. Self-Check

- [x] I selected one provisional lane.
- [x] I stated the decision I want to support.
- [x] I stated the action someone could take.
- [x] I described the cost of a wrong recommendation.
- [x] I included at least two real numbers from the starter data.
- [x] I explained why this is a prioritization problem, not simply a model-training task.
- [x] I used careful language about association and causation.
- [x] I will treat the lane as provisional and can change it based on later analysis.